workflows:
  ios-app-store:
    name: iOS App Store
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      flutter: stable
      xcode: 26
      vars:
        BUNDLE_ID: com.fertiliza.app
    scripts:
      - name: Disable Swift Package Manager
        script: |
          flutter config --no-enable-swift-package-manager
      - name: Set Bundle ID
        script: |
          OLD_BUNDLE_ID=$(xcode-project detect-bundle-id --project=$CM_BUILD_DIR/ios/Runner.xcodeproj --target=Runner)
          echo "Bundle ID actual: $OLD_BUNDLE_ID"
          echo "Cambiando a: $BUNDLE_ID"
          sed -i '' "s/$OLD_BUNDLE_ID/$BUNDLE_ID/g" $CM_BUILD_DIR/ios/Runner.xcodeproj/project.pbxproj
      - name: Fetch or create signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles --verbose
      - name: Install dependencies
        script: flutter pub get
      - name: Generate launcher icons
        script: dart run flutter_launcher_icons
      - name: Install pods
        script: |
          cd $CM_BUILD_DIR/ios
          rm -rf Pods Podfile.lock .symlinks
          pod install --repo-update
      - name: Build IPA
        script: |
          flutter build ipa --release --export-options-plist=$HOME/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true